model_list:
  - model_name: openrouter/openai/gpt-oss-120b
    litellm_params:
      model: openrouter/openai/gpt-oss-120b
      api_key: os.environ/OPENROUTER_API_KEY

  - model_name: openrouter/openai/gpt-oss-20b
    litellm_params:
      model: openrouter/openai/gpt-oss-20b
      api_key: os.environ/OPENROUTER_API_KEY

  - model_name: openrouter/google/gemini-2.0-flash-001
    litellm_params:
      model: openrouter/google/gemini-2.0-flash-001
      api_key: os.environ/OPENROUTER_API_KEY

  - model_name: openrouter/google/gemini-2.5-flash
    litellm_params:
      model: openrouter/google/gemini-2.5-flash
      api_key: os.environ/OPENROUTER_API_KEY

  - model_name: openrouter/google/gemini-3-flash-preview
    litellm_params:
      model: openrouter/google/gemini-3-flash-preview
      api_key: os.environ/OPENROUTER_API_KEY

  - model_name: openrouter/openai/gpt-4.1-mini
    litellm_params:
      model: openrouter/openai/gpt-4.1-mini
      api_key: os.environ/OPENROUTER_API_KEY

  - model_name: openrouter/openai/gpt-4.1-nano
    litellm_params:
      model: openrouter/openai/gpt-4.1-nano
      api_key: os.environ/OPENROUTER_API_KEY

  - model_name: openrouter/openai/gpt-5-nano
    litellm_params:
      model: openrouter/openai/gpt-5-nano
      api_key: os.environ/OPENROUTER_API_KEY

  - model_name: openrouter/openai/gpt-4o-mini
    litellm_params:
      model: openrouter/openai/gpt-4o-mini
      api_key: os.environ/OPENROUTER_API_KEY

  - model_name: openrouter/openai/gpt-5-mini
    litellm_params:
      model: openrouter/openai/gpt-5-mini
      api_key: os.environ/OPENROUTER_API_KEY

  - model_name: openrouter/openai/gpt-4o-mini-2024-07-18
    litellm_params:
      model: openrouter/openai/gpt-4o-mini-2024-07-18
      api_key: os.environ/OPENROUTER_API_KEY

  - model_name: openrouter/openai/gpt-5.1-codex-mini
    litellm_params:
      model: openrouter/openai/gpt-5.1-codex-mini
      api_key: os.environ/OPENROUTER_API_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
